name: deploy

on:
  push:
    branches:
      - "main"

env:
  VITE_API_KEY: ${{ secrets.VITE_API_KEY }}
  VITE_APP_ID: ${{ secrets.VITE_APP_ID }}
  VITE_AUTH_DOMAIN: ${{ secrets.VITE_AUTH_DOMAIN }}
  VITE_MEASUREMENT_ID: ${{ secrets.VITE_MEASUREMENT_ID }}
  VITE_MESSAGING_SENDER_ID: ${{ secrets.VITE_MESSAGING_SENDER_ID }}
  VITE_PROJECT_ID: ${{ secrets.VITE_PROJECT_ID }}
  VITE_STORAGE_BUCKET: ${{ secrets.VITE_STORAGE_BUCKET }}

jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
          registry-url: https://registry.npmjs.org/
      - run: npm ci && npm test

  bump:
    needs: [qa]
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - run: npm ci && npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs: [bump]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_CALYSTONE_A5BDF }}"
          projectId: calystone-a5bdf
          channelId: live
